package cn.kotlincloud.user.front.entity.model;

import io.jboot.db.annotation.Table;
import cn.kotlincloud.user.front.entity.base.BaseUserinfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "userinfo", primaryKey = "userId")
public class Userinfo extends BaseUserinfo<Userinfo> {
	
}
