package cn.kotlincloud.user.front.entity.model;

import io.jboot.db.annotation.Table;
import cn.kotlincloud.user.front.entity.base.BaseWebnet;

/**
 * Generated by Jboot.
 */
@Table(tableName = "webnet", primaryKey = "code,id")
public class Webnet extends BaseWebnet<Webnet> {
	
}
