package cn.kotlincloud.user.front.entity.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends JbootModel<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setUserByName(java.lang.String userByName) {
		set("userByName", userByName);
	}
	
	public java.lang.String getUserByName() {
		return getStr("userByName");
	}

	public void setPwdId(java.lang.Integer pwdId) {
		set("pwdId", pwdId);
	}
	
	public java.lang.Integer getPwdId() {
		return getInt("pwdId");
	}

	public void setUserEmail(java.lang.String userEmail) {
		set("userEmail", userEmail);
	}
	
	public java.lang.String getUserEmail() {
		return getStr("userEmail");
	}

	public void setUserType(java.lang.Integer userType) {
		set("userType", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public void setUserIconUrl(java.lang.String userIconUrl) {
		set("userIconUrl", userIconUrl);
	}
	
	public java.lang.String getUserIconUrl() {
		return getStr("userIconUrl");
	}

	public void setQqOpenId(java.lang.String qqOpenId) {
		set("qqOpenId", qqOpenId);
	}
	
	public java.lang.String getQqOpenId() {
		return getStr("qqOpenId");
	}

	public void setWxOpenId(java.lang.String wxOpenId) {
		set("wxOpenId", wxOpenId);
	}
	
	public java.lang.String getWxOpenId() {
		return getStr("wxOpenId");
	}

	public void setUserMobile(java.lang.String userMobile) {
		set("userMobile", userMobile);
	}
	
	public java.lang.String getUserMobile() {
		return getStr("userMobile");
	}

	public void setFaceId(java.lang.Integer faceId) {
		set("face_id", faceId);
	}
	
	public java.lang.Integer getFaceId() {
		return getInt("face_id");
	}

	public void setPubtime(java.util.Date pubtime) {
		set("pubtime", pubtime);
	}
	
	public java.util.Date getPubtime() {
		return get("pubtime");
	}

}
