package cn.kotlincloud.user.front.entity.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWebnet<M extends BaseWebnet<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setSubtitle(java.lang.String subtitle) {
		set("subtitle", subtitle);
	}
	
	public java.lang.String getSubtitle() {
		return getStr("subtitle");
	}

	public void setKeyword(java.lang.String keyword) {
		set("keyword", keyword);
	}
	
	public java.lang.String getKeyword() {
		return getStr("keyword");
	}

	public void setDomainName(java.lang.String domainName) {
		set("domain_name", domainName);
	}
	
	public java.lang.String getDomainName() {
		return getStr("domain_name");
	}

	public void setAuthorizationCode(java.lang.String authorizationCode) {
		set("Authorization_code", authorizationCode);
	}
	
	public java.lang.String getAuthorizationCode() {
		return getStr("Authorization_code");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}
	
	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setLogoUrl(java.lang.String logoUrl) {
		set("logo_url", logoUrl);
	}
	
	public java.lang.String getLogoUrl() {
		return getStr("logo_url");
	}

	public void setCdnUrl(java.lang.String cdnUrl) {
		set("cdn_url", cdnUrl);
	}
	
	public java.lang.String getCdnUrl() {
		return getStr("cdn_url");
	}

	public void setIcpNumber(java.lang.String icpNumber) {
		set("icp_number", icpNumber);
	}
	
	public java.lang.String getIcpNumber() {
		return getStr("icp_number");
	}

	public void setBeianNumber(java.lang.String beianNumber) {
		set("beian_number", beianNumber);
	}
	
	public java.lang.String getBeianNumber() {
		return getStr("beian_number");
	}

	public void setStatistical(java.lang.String statistical) {
		set("statistical", statistical);
	}
	
	public java.lang.String getStatistical() {
		return getStr("statistical");
	}

	public void setCopyrightInformation(java.lang.String copyrightInformation) {
		set("Copyright_information", copyrightInformation);
	}
	
	public java.lang.String getCopyrightInformation() {
		return getStr("Copyright_information");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public void setCreteTime(java.util.Date creteTime) {
		set("crete_time", creteTime);
	}
	
	public java.util.Date getCreteTime() {
		return get("crete_time");
	}

	public void setUpdateUserId(java.lang.Integer updateUserId) {
		set("update_user_id", updateUserId);
	}
	
	public java.lang.Integer getUpdateUserId() {
		return getInt("update_user_id");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
