package cn.kotlincloud.user.service.entity.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserType<M extends BaseUserType<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTypeCode(java.lang.Integer typeCode) {
		set("typeCode", typeCode);
	}
	
	public java.lang.Integer getTypeCode() {
		return getInt("typeCode");
	}

	public void setTyepName(java.lang.String tyepName) {
		set("tyepName", tyepName);
	}
	
	public java.lang.String getTyepName() {
		return getStr("tyepName");
	}

	public void setAppId(java.lang.Integer appId) {
		set("appId", appId);
	}
	
	public java.lang.Integer getAppId() {
		return getInt("appId");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("createUserId", createUserId);
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("createUserId");
	}

	public void setUpdateUserId(java.lang.Integer updateUserId) {
		set("updateUserId", updateUserId);
	}
	
	public java.lang.Integer getUpdateUserId() {
		return getInt("updateUserId");
	}

}
