package cn.kotlincloud.user.service.entity.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends JbootModel<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}
	
	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setUserCode(java.lang.String userCode) {
		set("userCode", userCode);
	}
	
	public java.lang.String getUserCode() {
		return getStr("userCode");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("userName");
	}

	public void setUserByName(java.lang.String userByName) {
		set("userByName", userByName);
	}
	
	public java.lang.String getUserByName() {
		return getStr("userByName");
	}

	public void setUserSex(java.lang.Integer userSex) {
		set("userSex", userSex);
	}
	
	public java.lang.Integer getUserSex() {
		return getInt("userSex");
	}

	public void setPwdId(java.lang.String pwdId) {
		set("pwdId", pwdId);
	}
	
	public java.lang.String getPwdId() {
		return getStr("pwdId");
	}

	public void setUserEmail(java.lang.String userEmail) {
		set("userEmail", userEmail);
	}
	
	public java.lang.String getUserEmail() {
		return getStr("userEmail");
	}

	public void setUserType(java.lang.Integer userType) {
		set("userType", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public void setUserIconUrl(java.lang.String userIconUrl) {
		set("userIconUrl", userIconUrl);
	}
	
	public java.lang.String getUserIconUrl() {
		return getStr("userIconUrl");
	}

	public void setQqOpenId(java.lang.String qqOpenId) {
		set("qqOpenId", qqOpenId);
	}
	
	public java.lang.String getQqOpenId() {
		return getStr("qqOpenId");
	}

	public void setWxOpenId(java.lang.String wxOpenId) {
		set("wxOpenId", wxOpenId);
	}
	
	public java.lang.String getWxOpenId() {
		return getStr("wxOpenId");
	}

	public void setUserMobile(java.lang.String userMobile) {
		set("userMobile", userMobile);
	}
	
	public java.lang.String getUserMobile() {
		return getStr("userMobile");
	}

	public void setFaceId(java.lang.Integer faceId) {
		set("face_id", faceId);
	}
	
	public java.lang.Integer getFaceId() {
		return getInt("face_id");
	}

	public void setVoiceprintId(java.lang.Integer voiceprintId) {
		set("voiceprintId", voiceprintId);
	}
	
	public java.lang.Integer getVoiceprintId() {
		return getInt("voiceprintId");
	}

	public void setAppId(java.lang.Integer appId) {
		set("appId", appId);
	}
	
	public java.lang.Integer getAppId() {
		return getInt("appId");
	}

	public void setPubtime(java.util.Date pubtime) {
		set("pubtime", pubtime);
	}
	
	public java.util.Date getPubtime() {
		return get("pubtime");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setLanguage(java.lang.String language) {
		set("language", language);
	}
	
	public java.lang.String getLanguage() {
		return getStr("language");
	}

}
