package cn.kotlincloud.user.service.entity.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAppinfo<M extends BaseAppinfo<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAppkey(java.lang.String appkey) {
		set("appkey", appkey);
	}
	
	public java.lang.String getAppkey() {
		return getStr("appkey");
	}

	public void setServicekey(java.lang.String servicekey) {
		set("servicekey", servicekey);
	}
	
	public java.lang.String getServicekey() {
		return getStr("servicekey");
	}

	public void setAppName(java.lang.String appName) {
		set("appName", appName);
	}
	
	public java.lang.String getAppName() {
		return getStr("appName");
	}

	public void setAppType(java.lang.String appType) {
		set("appType", appType);
	}
	
	public java.lang.String getAppType() {
		return getStr("appType");
	}

	public void setAppPackage(java.lang.String appPackage) {
		set("appPackage", appPackage);
	}
	
	public java.lang.String getAppPackage() {
		return getStr("appPackage");
	}

	public void setAppUrl(java.lang.String appUrl) {
		set("appUrl", appUrl);
	}
	
	public java.lang.String getAppUrl() {
		return getStr("appUrl");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setCreatUser(java.lang.Integer creatUser) {
		set("creatUser", creatUser);
	}
	
	public java.lang.Integer getCreatUser() {
		return getInt("creatUser");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setUpdateUser(java.lang.Integer updateUser) {
		set("updateUser", updateUser);
	}
	
	public java.lang.Integer getUpdateUser() {
		return getInt("updateUser");
	}

}
