package cn.kotlincloud.user.service.entity.model;

import io.jboot.db.annotation.Table;
import cn.kotlincloud.user.service.entity.base.BaseAppinfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "appinfo", primaryKey = "id")
public class Appinfo extends BaseAppinfo<Appinfo> {
	
}
