package cn.kotlincloud.user.service.entity.model;

import io.jboot.db.annotation.Table;
import cn.kotlincloud.user.service.entity.base.BaseUserPwd;

/**
 * Generated by Jboot.
 */
@Table(tableName = "userPwd", primaryKey = "id,pwdCode")
public class UserPwd extends BaseUserPwd<UserPwd> {
	
}
