package cn.kotlincloud.user.service.entity.model;

import io.jboot.db.annotation.Table;
import cn.kotlincloud.user.service.entity.base.BaseUserType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "userType", primaryKey = "id")
public class UserType extends BaseUserType<UserType> {
	
}
